### ISSUE TITLE
1.1.3版本 使用java调用自定义布局时，报类型转换异常

### ISSUE THREAD

**Issue by jinlinupup** [yinshuai0324/ToastX#3]
Caused by: java.lang.ClassCastException: com.google.android.material.snackbar.Snackbar$SnackbarLayout cannot be cast to com.app.toast.snackbar.BaseTransientBottomBar$SnackbarBaseLayout
        at com.app.toast.snackbar.BaseTransientBottomBar.<init>(BaseTransientBottomBar.java:409)
        at com.app.toast.snackbar.Snackbar.<init>(Snackbar.java:124)
        at com.app.toast.snackbar.Snackbar.makeInternal(Snackbar.java:228)
        at com.app.toast.snackbar.Snackbar.make(Snackbar.java:170)
        at com.app.toast.snackbar.SnackBarX.show(SnackBarX.kt:143)

**Comment by jinlinupup** [comment]
参照demo的使用方式，也还是会报该异常

**Comment by yinshuai0324** [comment]
有复现的代码吗？我用Java测试没有复现这个问题

**Comment by jinlinupup** [comment]
感谢您的回复。
View toastRoot =  LayoutInflater.from(MainActivity.this).inflate(R.layout.custom_ruler_layout, null);
 TextView tvToastText = (TextView) toastRoot.findViewById(R.id.toast_text);
 TextView textJump = (TextView) toastRoot.findViewById(R.id.textJump);
textJump.setOnClickListener(new View.OnClickListener() {
 @Override
 public void onClick(View v) {}
}
ToastX.with(MainActivity.this)
        .customizeView(toastRoot)
        .animationMode(ToastX.ANIM_MODEL_SLIDE) //动画模式 弹出或者渐变
        .position(ToastX.POSITION_BOTTOM) //显示的位置 顶部或者底部
        .duration(3000) //显示的时间 单位ms
        .show();

--------------------
调用代码如上所示。我新开的项目使用没有啥问题，在一个老项目上调用就会报上面的类型转换错误。

**Comment by yinshuai0324** [comment]
可以尝试在您的老项目上用下Design库的Snackbar。看是否表现正常。本库就是基于Snackbar改的。如果直接使用Snackbar表现正常的话 看能否提供可以复现的demo

**Comment by wo376913879** [comment]
在华为平板 MRR-W29上 会出现这个错误

**Comment by chende008** [comment]
我也碰到这样的情况，根据调试走到了这里：
     final SnackbarContentLayout content =SnackbarContentLayout)
                        inflater.inflate( hasSnackbarContentStyleAttrs(context) ? R.layout.mtrl_layout_snackbar_include : R.layout.design_layout_snackbar_include, parent, false);
        final Snackbar snackbar = new Snackbar(context, parent, content, content);

hasSnackbarContentStyleAttrs(context) 的值为false，所以取R.layout.design_layout_snackbar_include这个布局，然后就使用系统的snackar，然后就报了类型转换异常

@yinshuai0324 没太懂这里的逻辑，麻烦大佬有时间看看？
